// <auto-generated />
namespace HoLaBus.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddLenght100FromEmailGuest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddLenght100FromEmailGuest));
        
        string IMigrationMetadata.Id
        {
            get { return "201811211553437_AddLenght100FromEmailGuest"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
