// <auto-generated />
namespace HoLaBus.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddNewColumToSeatInforforce : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddNewColumToSeatInforforce));
        
        string IMigrationMetadata.Id
        {
            get { return "201810141614496_AddNewColumToSeatInfor-force"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
